// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo01.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_demo01_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_demo01_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "info.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_demo01_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_demo01_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_demo01_2eproto;
class Preson;
struct PresonDefaultTypeInternal;
extern PresonDefaultTypeInternal _Preson_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Preson* Arena::CreateMaybeMessage<::Preson>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum CoLor : int {
  Red = 0,
  Green = 6,
  Blue = 9,
  CoLor_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CoLor_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CoLor_IsValid(int value);
constexpr CoLor CoLor_MIN = Red;
constexpr CoLor CoLor_MAX = Blue;
constexpr int CoLor_ARRAYSIZE = CoLor_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CoLor_descriptor();
template<typename T>
inline const std::string& CoLor_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CoLor>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CoLor_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CoLor_descriptor(), enum_t_value);
}
inline bool CoLor_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CoLor* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CoLor>(
    CoLor_descriptor(), name, value);
}
// ===================================================================

class Preson final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Preson) */ {
 public:
  inline Preson() : Preson(nullptr) {}
  ~Preson() override;
  explicit PROTOBUF_CONSTEXPR Preson(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Preson(const Preson& from);
  Preson(Preson&& from) noexcept
    : Preson() {
    *this = ::std::move(from);
  }

  inline Preson& operator=(const Preson& from) {
    CopyFrom(from);
    return *this;
  }
  inline Preson& operator=(Preson&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Preson& default_instance() {
    return *internal_default_instance();
  }
  static inline const Preson* internal_default_instance() {
    return reinterpret_cast<const Preson*>(
               &_Preson_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Preson& a, Preson& b) {
    a.Swap(&b);
  }
  inline void Swap(Preson* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Preson* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Preson* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Preson>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Preson& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Preson& from) {
    Preson::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Preson* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Preson";
  }
  protected:
  explicit Preson(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kSexFieldNumber = 3,
    kInfoFieldNumber = 6,
    kIdFieldNumber = 1,
    kAgeFieldNumber = 4,
    kCoLorFieldNumber = 5,
  };
  // repeated bytes name = 2;
  int name_size() const;
  private:
  int _internal_name_size() const;
  public:
  void clear_name();
  const std::string& name(int index) const;
  std::string* mutable_name(int index);
  void set_name(int index, const std::string& value);
  void set_name(int index, std::string&& value);
  void set_name(int index, const char* value);
  void set_name(int index, const void* value, size_t size);
  std::string* add_name();
  void add_name(const std::string& value);
  void add_name(std::string&& value);
  void add_name(const char* value);
  void add_name(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_name();
  private:
  const std::string& _internal_name(int index) const;
  std::string* _internal_add_name();
  public:

  // string sex = 3;
  void clear_sex();
  const std::string& sex() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sex(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sex();
  PROTOBUF_NODISCARD std::string* release_sex();
  void set_allocated_sex(std::string* sex);
  private:
  const std::string& _internal_sex() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sex(const std::string& value);
  std::string* _internal_mutable_sex();
  public:

  // .Info info = 6;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::Info& info() const;
  PROTOBUF_NODISCARD ::Info* release_info();
  ::Info* mutable_info();
  void set_allocated_info(::Info* info);
  private:
  const ::Info& _internal_info() const;
  ::Info* _internal_mutable_info();
  public:
  void unsafe_arena_set_allocated_info(
      ::Info* info);
  ::Info* unsafe_arena_release_info();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 age = 4;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // .CoLor CoLor = 5;
  void clear_color();
  ::CoLor color() const;
  void set_color(::CoLor value);
  private:
  ::CoLor _internal_color() const;
  void _internal_set_color(::CoLor value);
  public:

  // @@protoc_insertion_point(class_scope:Preson)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sex_;
    ::Info* info_;
    int32_t id_;
    int32_t age_;
    int color_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_demo01_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Preson

// int32 id = 1;
inline void Preson::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Preson::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Preson::id() const {
  // @@protoc_insertion_point(field_get:Preson.id)
  return _internal_id();
}
inline void Preson::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Preson::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Preson.id)
}

// repeated bytes name = 2;
inline int Preson::_internal_name_size() const {
  return _impl_.name_.size();
}
inline int Preson::name_size() const {
  return _internal_name_size();
}
inline void Preson::clear_name() {
  _impl_.name_.Clear();
}
inline std::string* Preson::add_name() {
  std::string* _s = _internal_add_name();
  // @@protoc_insertion_point(field_add_mutable:Preson.name)
  return _s;
}
inline const std::string& Preson::_internal_name(int index) const {
  return _impl_.name_.Get(index);
}
inline const std::string& Preson::name(int index) const {
  // @@protoc_insertion_point(field_get:Preson.name)
  return _internal_name(index);
}
inline std::string* Preson::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:Preson.name)
  return _impl_.name_.Mutable(index);
}
inline void Preson::set_name(int index, const std::string& value) {
  _impl_.name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:Preson.name)
}
inline void Preson::set_name(int index, std::string&& value) {
  _impl_.name_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:Preson.name)
}
inline void Preson::set_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Preson.name)
}
inline void Preson::set_name(int index, const void* value, size_t size) {
  _impl_.name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Preson.name)
}
inline std::string* Preson::_internal_add_name() {
  return _impl_.name_.Add();
}
inline void Preson::add_name(const std::string& value) {
  _impl_.name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Preson.name)
}
inline void Preson::add_name(std::string&& value) {
  _impl_.name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Preson.name)
}
inline void Preson::add_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Preson.name)
}
inline void Preson::add_name(const void* value, size_t size) {
  _impl_.name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Preson.name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Preson::name() const {
  // @@protoc_insertion_point(field_list:Preson.name)
  return _impl_.name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Preson::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:Preson.name)
  return &_impl_.name_;
}

// string sex = 3;
inline void Preson::clear_sex() {
  _impl_.sex_.ClearToEmpty();
}
inline const std::string& Preson::sex() const {
  // @@protoc_insertion_point(field_get:Preson.sex)
  return _internal_sex();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Preson::set_sex(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sex_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Preson.sex)
}
inline std::string* Preson::mutable_sex() {
  std::string* _s = _internal_mutable_sex();
  // @@protoc_insertion_point(field_mutable:Preson.sex)
  return _s;
}
inline const std::string& Preson::_internal_sex() const {
  return _impl_.sex_.Get();
}
inline void Preson::_internal_set_sex(const std::string& value) {
  
  _impl_.sex_.Set(value, GetArenaForAllocation());
}
inline std::string* Preson::_internal_mutable_sex() {
  
  return _impl_.sex_.Mutable(GetArenaForAllocation());
}
inline std::string* Preson::release_sex() {
  // @@protoc_insertion_point(field_release:Preson.sex)
  return _impl_.sex_.Release();
}
inline void Preson::set_allocated_sex(std::string* sex) {
  if (sex != nullptr) {
    
  } else {
    
  }
  _impl_.sex_.SetAllocated(sex, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sex_.IsDefault()) {
    _impl_.sex_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Preson.sex)
}

// int32 age = 4;
inline void Preson::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t Preson::_internal_age() const {
  return _impl_.age_;
}
inline int32_t Preson::age() const {
  // @@protoc_insertion_point(field_get:Preson.age)
  return _internal_age();
}
inline void Preson::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void Preson::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:Preson.age)
}

// .CoLor CoLor = 5;
inline void Preson::clear_color() {
  _impl_.color_ = 0;
}
inline ::CoLor Preson::_internal_color() const {
  return static_cast< ::CoLor >(_impl_.color_);
}
inline ::CoLor Preson::color() const {
  // @@protoc_insertion_point(field_get:Preson.CoLor)
  return _internal_color();
}
inline void Preson::_internal_set_color(::CoLor value) {
  
  _impl_.color_ = value;
}
inline void Preson::set_color(::CoLor value) {
  _internal_set_color(value);
  // @@protoc_insertion_point(field_set:Preson.CoLor)
}

// .Info info = 6;
inline bool Preson::_internal_has_info() const {
  return this != internal_default_instance() && _impl_.info_ != nullptr;
}
inline bool Preson::has_info() const {
  return _internal_has_info();
}
inline const ::Info& Preson::_internal_info() const {
  const ::Info* p = _impl_.info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Info&>(
      ::_Info_default_instance_);
}
inline const ::Info& Preson::info() const {
  // @@protoc_insertion_point(field_get:Preson.info)
  return _internal_info();
}
inline void Preson::unsafe_arena_set_allocated_info(
    ::Info* info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.info_);
  }
  _impl_.info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Preson.info)
}
inline ::Info* Preson::release_info() {
  
  ::Info* temp = _impl_.info_;
  _impl_.info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Info* Preson::unsafe_arena_release_info() {
  // @@protoc_insertion_point(field_release:Preson.info)
  
  ::Info* temp = _impl_.info_;
  _impl_.info_ = nullptr;
  return temp;
}
inline ::Info* Preson::_internal_mutable_info() {
  
  if (_impl_.info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Info>(GetArenaForAllocation());
    _impl_.info_ = p;
  }
  return _impl_.info_;
}
inline ::Info* Preson::mutable_info() {
  ::Info* _msg = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:Preson.info)
  return _msg;
}
inline void Preson::set_allocated_info(::Info* info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.info_);
  }
  if (info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(info));
    if (message_arena != submessage_arena) {
      info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.info_ = info;
  // @@protoc_insertion_point(field_set_allocated:Preson.info)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::CoLor> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CoLor>() {
  return ::CoLor_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_demo01_2eproto
